# Generated by Django 2.2.3 on 2019-07-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='video',
            field=models.URLField(null=True),
        ),
    ]