# Generated by Django 2.2.3 on 2019-08-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_blog_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Monday', models.IntegerField()),
                ('Tuesday', models.IntegerField()),
                ('Wednesday', models.IntegerField()),
                ('Thursday', models.IntegerField()),
                ('Friday', models.IntegerField()),
                ('Saturday', models.IntegerField()),
                ('Sunday', models.IntegerField()),
            ],
            options={
                'db_table': 'chart',
            },
        ),
    ]